### PR TITLE
Create highlevel_diagram.md

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
high-level diagram https://kbase-jira.atlassian.net/browse/SAM-205

### CODE REVIEW

**Comment by dauglyon** [comment]
My only note is we may want to add a node/edge for workspace and it's automatic updates of sample permissions

**Comment by dauglyon** [comment]
Otherwise looks good, aligns with my understanding of things

**Comment by Tianhao-Gu** [comment]
> My only note is we may want to add a node/edge for workspace and it's automatic updates of sample permissions

👍  good idea. added a workspace node.

**Comment by scanon** [comment]
@Tianhao-Gu I just merged Erik's PR that moves some things around.  Can you see if you diagram needs to move and should we reference it somewhere so it shows up?

**Comment by Tianhao-Gu** [comment]
> @Tianhao-Gu I just merged Erik's PR that moves some things around. Can you see if you diagram needs to move and should we reference it somewhere so it shows up?

👍  moved it to the design folder.

**Pull request merged**
