### PR TITLE
Add GHCR workflows

### PR DESCRIPTION
**Pull request by dauglyon**
Adds .github workflows for:
- build/push image from any PR `#X` into `master` to `ghcr.io/kbase/sample_service:pr-X`
- build/push image from `master@HEAD` to `ghcr.io/kbase/sample_service:latest`

Also adds, but may not be needed:
- build/push image from any PR `#X` into `develop` to `ghcr.io/kbase/sample_service-develop:pr-X`
- build/push image from `develop@HEAD` to `ghcr.io/kbase/sample_service-develop:latest`

### CODE REVIEW

**Comment by eapearson** [comment]
Aren't there prebuilt GitHub actions for build and push images (rather than doing it in a script)?
Also it would be useful to build and image for a release, using the release version as the tag.

**Comment by dauglyon** [comment]
@eapearson I'm not sure what you mean by prebuilt. There are templates for creating YAML files like the ones here, but these come from https://github.com/kbase/init-sidecar/blob/develop/.github/workflows/ReleaseCycleProposal.md and are mostly just copy/pasted as per @jsfillman's advice

**Comment by dauglyon** [comment]
I like the idea of basing images on git semver tags, but it doesnt seem to be what we do elsewhere

**Comment by eapearson** [comment]
> I like the idea of basing images on git semver tags, but it doesnt seem to be what we do elsewhere

Images with the release tag / semver is growing as a best practice in kbase, even if not practiced widely. Or, at least - when I added this to kbase-ui builds I checked with Shane to confirm that this would be considered both acceptable and an improvement, and he concurred.

It helps ease rollbacks after a deploy has been finalized, and helps folks quickly determine the version deployed.

**Comment by eapearson** [comment]
> @eapearson I'm not sure what you mean by prebuilt. There are templates for creating YAML files like the ones here, but these come from https://github.com/kbase/init-sidecar/blob/develop/.github/workflows/ReleaseCycleProposal.md and are mostly just copy/pasted as per @jsfillman's advice

What I mean are canned actions, like docker/setup-buildx-action, docker/login-action, docker/build-push-action, 

E.g. from kbase-ui:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # hmm, try this.
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          build-args: |
            BUILD_CONFIG=prod
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
            BRANCH=${{ github.ref }}
            TAG=${{ github.ref }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/kbase-ui:latest
            ghcr.io/${{ github.repository_owner }}/kbase-ui:${{ env.CI_ACTION_REF_NAME }}
```

**Comment by scanon** [comment]
We can tweak this later.  I'm going to merge it so we can get some of this up and running.

**Pull request merged**
