### PR TITLE
adding 'percent' unit to Unit Registry

### PR DESCRIPTION
**Pull request by slebras**

### CODE REVIEW

**Comment by MrCreosote** [comment]
There seems to be formatting issues when making percent convertible to count: https://github.com/hgrecco/pint/issues/379#issuecomment-283642348

Do we not care about that?

**Comment by MrCreosote** [comment]
I think the issue is that a percentage can get converted to a straight count, which is usually not what you want. 50% can be converted to 0.5, etc. A percentage is a ratio, not a count.

**Comment by slebras** [comment]
True, I just figured it may make some operations easier in the future. Not sure its necessary though. I'll remove it

**Comment by MrCreosote** [comment]
LGTM

**Pull request merged**
